### ISSUE TITLE
Change required for AppCenter: Update screenshots

### ISSUE THREAD

**Issue by cassidyjames** [linuxhubit/shouldidoit#10]
Thanks for submitting your app to AppCenter! Per the publishing and update requirements, please update your screenshot as well to reflect the change in window button position:

- https://docs.elementary.io/develop/appcenter/publishing-requirements#appdata-and-oars
- https://docs.elementary.io/develop/appcenter/publishing-updates#updating-screenshots

Once you've made the requested change (and updated the AppData release description and version number), please make a new release and submit it to AppCenter.

**Comment by mirkobrombin** [comment]
I don't have elementary OS on my pc **at the moment** and I would have to configure a VM to be able to make a screenshot of latest version.

I will work on this as soon as I return to elementary, thanks for the tip.
