### ISSUE TITLE
AppData doesn't match the app

### ISSUE THREAD

**Issue by danirabbit** [linuxhubit/shouldidoit#11]
https://github.com/linuxhubit/shouldidoit/blob/1a7434cdcc11a10923e56db8ac8452cad0a659eb/data/com.github.linuxhubit.shouldidoit.appdata.xml.in#L7

It looks like this appdata was copied from somewhere else. It includes the name and description for a different app as well as someone else's copyright

**Comment by mirkobrombin** [comment]
Ah yes it is another my application, let me fix it
